version: '3.8'
services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: studentapp
      MYSQL_USER: sushant
      MYSQL_PASSWORD: sushant123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  tomcat:
    build: .
    container_name: studentapp
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  db_data:
