version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: studentapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studentapp
      MYSQL_USER: sushant
      MYSQL_PASSWORD: sushant123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studentapp_tomcat
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: studentapp
      MYSQL_USER: sushant
      MYSQL_PASSWORD: sushant123

volumes:
  db_data:
